#!/bin/bash

# Create necessary directories if they do not exist
mkdir -p web_dynamic/templates/
mkdir -p web_dynamic/static/

# Step 1: Copy files and directories if they exist
cp -r web_flask/static web_dynamic/
if [ -f web_flask/templates/100-hbnb.html ]; then
    cp web_flask/templates/100-hbnb.html web_dynamic/templates/
else
    cp web_flask/templates/8-hbnb.html web_dynamic/templates/0-hbnb.html
fi
cp web_flask/__init__.py web_dynamic/
cp web_flask/100-hbnb.py web_dynamic/0-hbnb.py

# Step 2: Rename files
mv web_dynamic/templates/100-hbnb.html web_dynamic/templates/0-hbnb.html 2>/dev/null

# Step 3: Update the route in 0-hbnb.py
sed -i 's@app.route("/100-hbnb/")@app.route("/0-hbnb/")@' web_dynamic/0-hbnb.py

